export const GET_THINGS_FROM_DB = 'GET_THINGS_FROM_DB';
export const GET_ALL_THINGS_FROM_DB = 'GET_ALL_THINGS_FROM_DB';
export const POST_THING_DB = 'POST_THING_DB';
export const PUT_THING_DB = 'PUT_THING_DB';
export const DELETE_THING_DB = 'DELETE_THING_DB';
